[Hoo/BC] 로또 2단계 - 보너스 번호 추가
codesquad-members-2022/java-lotto pull request #40
Opened 2022-02-24 08:03 UTC by honeySleepr

안녕하세요! Hoo / BC 조 입니다. 
리뷰어님 항상 감사드립니다.🤗

로또 2단계 보너스 번호 추가 및 리팩토링을 진행하였습니다.

주요 변경사항으로는..
*  보너스 번호 기능 추가(랭크에 2등 추가, 결과값 계산 로직 변경)
*  일반 컬렉션으로 사용하던 값들을 일급컬렉션 타입으로 변경
*  각 객체의 역할에 맞게 책임 재분배(로직 이동)
*  메서드, 변수 네이밍 수정
*  메서드가 한 역할만 하도록 메서드 추출

2022-02-26 01:19 UTC, wheejuni requested changes
전반적으로 좋습니다 💯 
코멘트 몇 개만 참고해 주세요~

2022-02-26 01:19 UTC, wheejuni commented on src/main/java/domain/Lotto.java
> +    public String toString() {
`java.lang.Object` 에 있는 메소드를 오버라이드할 때는 클래스 최하단에 해주세요~

2022-02-26 01:19 UTC, wheejuni commented on src/main/java/view/InputValidator.java
> +class InputValidator {
무슨 이유에선지 이 클래스엔 유난히 접근 제어자가 많이 빠져 있네요...

2022-02-26 01:19 UTC, wheejuni commented on src/main/java/view/InputValidator.java
> +        return new IllegalArgumentException("int 범위 내로 입력해주세요.");
예외를 던져야 한다면 여기서 직접 던지면 됩니다. 굳이 `return` 해서 로직을 꼬아 놓을 필요가 없고요.
특정 상황에서 특정 문구로 이렇게 예외가 던져지기를 원한다면 이미 제공되는 예외들 말고 별도의 커스텀 예외를 작성하는 것이 좋겠습니다.

2022-02-26 11:06 UTC, who-hoo commented on src/main/java/domain/Lotto.java
> +    public String toString() {
반영완료하였습니다. 감사합니다.
추가로 `Object` 외의 인터페이스나 상위 클래스의 메소드를 오버라이드 할때에도 클래스 하단에 상속 계층 순으로 하단에 위치시키는 것이 관례인지 궁금합니다..

2022-02-26 11:07 UTC, who-hoo commented on src/main/java/view/InputValidator.java
> +class InputValidator {
InputValidator 클래스는 InputView에서만 사용하므로 package-private 적용해도 된다고 판단하여 의도적으로 접근 제어자를 (default)로 설정해두었습니다!

2022-02-26 11:13 UTC, who-hoo commented on src/main/java/view/InputValidator.java
> +        return new IllegalArgumentException("int 범위 내로 입력해주세요.");
반영완료하였습니다. 감사합니다.
저희는 커스텀 예외를 작성하는 것보다 표준 예외를 재사용 했을 때 얻는 이점이 더 많다고 판단하여 표준 예외를 재사용 하였습니다. (커스텀 예외 작성 시 작성하는 비용과 다른 개발자가 커스텀 예외를 분석하는데 드는 비용 절약) IllegalArgumentException 만으로도 입력이 잘못 되어 발생한 예외상황이라는 것을 클라이언트에게 잘 알리고 있는 것 같은데, 특정 상황에서 특정 문구로 예외가 던져지기를 원할 때는 커스텀 예외를 작성하는 것이 일반적인가요?

2022-02-27 11:36 UTC, wheejuni commented on src/main/java/domain/Lotto.java
> +    public String toString() {
그건 아닙니다.

2022-02-27 11:38 UTC, wheejuni commented on src/main/java/view/InputValidator.java
> +class InputValidator {
그런 목적이라면 아예 이 클래스를 `InputView` 와 같은 파일에 위치시키는 것도 검토해볼만 합니다.
패키지 구조는 프로젝트가 진행되면서 언제든지 깨어지기 쉬워서, 특정 클래스에서만/패키지에서만 공개된 메소드/API를 사용할 거라고 판단하는 것은 대단히 위험합니다.

자바 클래스에 작성되는 접근 제어자는 **최대한의 접근 차단** 을 항상 목적으로 두어야 합니다. 아래 글을 읽고 생각을 가져보시는 것도 좋겠네요.

https://dev.to/cauchypeano/why-you-should-avoid-package-private-scope-in-java-anl

2022-02-27 11:40 UTC, wheejuni commented on src/main/java/view/InputValidator.java
> +        return new IllegalArgumentException("int 범위 내로 입력해주세요.");
커맨드 + 클릭으로 한번 쫓아가면 그만이라 커스텀 예외를 분석하는데 그렇게 큰 비용이 들 것 같진 않군요. 
커스텀 예외를 사용해야 하는 가장 큰 이유는 APM 도구 등을 이용해서 애플리케이션을 분석할 때 오탐 가능성을 줄이고 불필요한 콘솔 로깅을 최소화하는 것에 있습니다.
예를 들어 예외 탐지 모니터링을 실행하는데 `IllegalArgumentException` 을 대상 예외로 설정하면 애플리케이션 레이어 외부에서 발생하는 모든 해당 예외가 다 탐지되겠죠(자바 애플리케이션에서 굉장히 흔한 예외니까요).
커스텀 예외를 작성해 해당 예외를 탐지대상으로 설정하면 훨씬 더 pinpoint 해서 에러를 탐지할 수 있고 오탐 가능성을 극적으로 줄일 수 있을 것 같습니다.
예외는 가능한 한 가장 구체적으로 작성해서 사용하는게 좋습니다.

2022-02-27 15:06 UTC, who-hoo commented on src/main/java/view/InputValidator.java
> +class InputValidator {
감사합니다! 반영 완료 하였습니다!

2022-02-27 15:08 UTC, who-hoo commented on src/main/java/view/InputValidator.java
> +        return new IllegalArgumentException("int 범위 내로 입력해주세요.");
한치 앞만 보고있었네요 모니터링은 생각도 못해봤었는데ㅎㅎ 감사합니다. 반영완료 하였습니다!

2022-02-27 15:08 UTC, honeySleepr commented
PR 리뷰 반영하였습니다. Merge 부탁드립니다 🙇‍♂️🙇‍♂️

2022-02-27 15:13 UTC, merged