[선을로/익조] 로또 3단계 - 수동구매 기능 추가
codesquad-members-2022/java-lotto pull request #42
Opened 2022-02-24 14:25 UTC by ikjo93

안녕하세요!! hounx!! 15팀(선을로/익조)입니다!!

"로또 2단계 - 보너스 번호 추가" 구현 부분과 관련하여, 작성한 소스 코드파일을 첨부드리오니 확인부탁드립니다. :)

※ 참고사항 : 클래스 역할과 책임, 이벤트 흐름도 등은 README 파일을 참고해주세요!!

감사합니다.

2022-02-24 16:16 UTC, tmdgusya requested changes
메소드 명에 기대되는 결과값에 아쉬운 부분이 있어 
해당 부분은 메소드 명을 수정하거나 바꿔주셔야 할거 같아요.

추상클래스 관련된 부분은 한번 고려해보시는걸 추천드려요 ㅎㅎ
지금 상태로 가도 좋으나 좀 더 좋은 방법이 있어보입니다.
그래도 좋은 고민을 하신 노력들이 보여요 👍

2022-02-24 16:16 UTC, tmdgusya commented on AutoLottoMaker.java
> +    }
저번 리뷰에서 말한 부분을 적용하셨군요
근데 한가지 궁금한 점이 있습니다. 
혹시 makeLottoNumber 자체가 interface 의 메소드여야 하지 않을까요?
둘다 makeLottoNumber 가 있을거 같아서요 만약 다른 클래스에 노출하기 싫다면 protected 를 쓸 수 있는 abstract class 도 사용을 고려해보시는 것도.

어렵겠지만 만약 추상클래스 였다면 어땠을지 한번 생각해보세요.

2022-02-24 16:16 UTC, tmdgusya commented on ManualLottoMaker.java
> +    private List<Integer> makeLottoNumber(String manualLottoNumber) {
이 interface 가 겹친다는 생각이 드시진 않나요 ㅎㅎ?
추상 클래스 한번 고려해보시죠

2022-02-24 16:16 UTC, tmdgusya commented on RankValue.java
> +        return NOTHING;
👍

2022-02-24 16:16 UTC, tmdgusya commented on UserInterface.java
> +            if (money > -1) break;
-1 은 무슨 뜻일까요 ㅎㅎ?
validateMoney 에서 int 가 나오나요?

2022-02-24 16:16 UTC, tmdgusya commented on Validation.java
> +    public int validateMoney(String userInput) {
보통 `is` 나 `validate` 에서는 boolean 값을 기대하지 않을까요?

2022-02-24 16:16 UTC, tmdgusya commented on Validation.java
> +    public int validateMoney(String userInput) {
이 부분은 한번 고려를 해보셔야 할거 같아요

2022-02-24 19:07 UTC, ikjo93 commented on AutoLottoMaker.java
> +    }
당초 LottoMaker 인터페이스를 통해 AutoLottoMaker와 ManualLottoMaker를 구현하고있었으나, 리뷰주신 사항과 같이 makeLottoNumber 메서드 역시도 LottoMaker를 구현하는 메서드로서 Override됨이 마땅하며, 아울러 이들간의 관계(LottoMaker ↔ Auto/ManualLottoMaker)는 is a kind of(~의 종류인) 관계로서 인터페이스 보다는 추상 클래스트를 통해 구현하는 것이 더 적합하다고 판단하여 추상클래스 형태로 변경 작업하였습니다.

2022-02-24 19:09 UTC, ikjo93 commented on ManualLottoMaker.java
> +    private List<Integer> makeLottoNumber(String manualLottoNumber) {
위에서 답변드린 사항과 동일합니다. 😁

<br/>

```
당초 LottoMaker 인터페이스를 통해 AutoLottoMaker와 ManualLottoMaker를 구현하고있었으나, 리뷰주신 사항과 같이 makeLottoNumber 메서드 역시도 LottoMaker를 구현하는 메서드로서 Override됨이 마땅하며, 아울러 이들간의 관계(LottoMaker ↔ Auto/ManualLottoMaker)는 is a kind of(~의 종류인) 관계로서 인터페이스 보다는 추상 클래스트를 통해 구현하는 것이 더 적합하다고 판단하여 추상클래스 형태로 변경 작업하였습니다.
```

2022-02-24 19:09 UTC, ikjo93 commented on RankValue.java
> +        return NOTHING;
🙇‍♂️

2022-02-24 19:10 UTC, ikjo93 commented on UserInterface.java
> +            if (money > -1) break;
당초 Validation 클래스에서 사용자 입력을 검증 시 어떤 메서드는 int로(당초 의도는 문자열 형태인 사용자 데이터를 정수로 반환하고자함이었습니다.) 그리고 어떤 메서드는 String으로 반환하는 등 반환 타입이 중구난방이었으나, 검증 메서드의 특성상 반환형은 boolean형이 더 적합하다고 판단하여 Validation 메서드의 반환형을 모두 boolean형으로 수정하였습니다.

2022-02-24 19:11 UTC, ikjo93 commented on Validation.java
> +    public int validateMoney(String userInput) {
위에서 답변드린 사항과 동일합니다. 😁

<br/>

```
당초 Validation 클래스에서 사용자 입력을 검증 시 어떤 메서드는 int로(당초 의도는 문자열 형태인 사용자 데이터를 정수로 반환하고자함이었습니다.) 그리고 어떤 메서드는 String으로 반환하는 등 반환 타입이 중구난방이었으나, 검증 메서드의 특성상 반환형은 boolean형이 더 적합하다고 판단하여 Validation 메서드의 반환형을 모두 boolean형으로 수정하였습니다.
```

2022-02-24 19:15 UTC, ikjo93 commented on Validation.java
> +    public int validateMoney(String userInput) {
늦은 시간에도 리뷰 주셔서 감사드립니다!! ✨ 막상 Pull Request를 하고 나니 생각이 짧았던 부분들과 미흡했던 부분들이 많았습니다. 다음에 제출할 때는 좀 더 신경 써서 제출드리겠습니다. 😂 아울러 Changes requested를 안주셨으면 이러한 부분들을 놓치고 그냥 지나쳤을 것 같았는데 다시 한 번 생각하게 해주셔서 감사드립니다. 🙏

2022-02-24 19:19 UTC, ikjo93 commented
늦은 시간에도 리뷰주셔서 감사드립니다!! ✨ 막상 Pull Request를 하고 나니 생각이 짧았던 부분들과 미흡했었던 부분들이 많았습니다. 다음부터는 제출하기 전에 좀 더 신경써서 제출드리겠습니다. 😂 아울러 만일 Changes requested가 아니었다면 생각하지 않고 그냥 넘어갔을 수도 있는 부분들이었는데 다시 한 번 생각할 수 있게 해주셔서 감사드립니다!! 🙏

2022-02-25 01:41 UTC, tmdgusya commented
> 

@ikjo93 
ㅎㅎ 페어로 잘 작성하시는거 같고 두분이서 학습을 잘 하시는 것 같네요.
아마 이번에 클래스를 나눠보시면서 많은 학습을 하셨을거 같네요.
수정하신거 올려주시면 머지해드리겠습니다.

2022-02-25 01:41 UTC, merged

2022-02-25 01:45 UTC, ikjo93 commented
@tmdgusya
감사합니다 로치님!! 이번 리뷰를 통해 저희 15팀 많이 배우게 되었습니다~! 🙏

2022-02-25 02:21 UTC, ikjo93 commented
@tmdgusya
로치님 😭 저희가 git 사용법이 미숙해서(😂) 실수로 Merge Pull Request를 눌러서 저희 이름으로 Merge가 된 거 같습니다 🤣 수정한 내용은 Origin에 Push 해놓은 상태였었는데(커밋 기록 9010a5b) 혹시 다시 Merge를 받도록 해야한다면 Revert 작업 해놓겠습니다..!!

2022-02-25 09:21 UTC, tmdgusya reviewed
리뷰 반영하느라 고생하셨습니다.
추상 클래스로 잘 바꾸신거 같아 기분이 좋네요 💯

2022-02-25 09:21 UTC, tmdgusya commented on LottoMaker.java
> +public abstract class LottoMaker {
👍

2022-02-25 09:21 UTC, tmdgusya commented on LottoMaker.java
> +    protected abstract List<Integer> makeLottoNumber();
제가 생각한것과 비슷하군요. 좋습니다 :)

시간 되시면 템플릿 메소드 패턴에 대해서 한번 훑어만 보세요. 따로 공부는 안하셔도 됩니다 ㅎㅎ
보시면 디자인 패턴에 대해서 감이 오실꺼에요.

2022-02-25 09:21 UTC, tmdgusya commented on Validation.java
> +    public boolean validateBonusNumber(String userInput) {
👍