[Sammy & K] 로또 3단계 - 수동구매 기능 추가
codesquad-members-2022/java-lotto pull request #47
Opened 2022-02-25 02:54 UTC by astraum

로또 3단계 완료하여 리뷰 요청 드립니다.

피와 살이 되는 피드백에 늘 감사합니다!

- [x] 입력한 금액, 자동 생성 숫자, 수동 생성 번호를 입력하도록 해야 한다.
- [x] 예외가 발생하는 부분에 대해 자바 Exception을 적용해 예외처리한다.
- [x] 사용자가 입력한 값에 대한 예외 처리를 철저히 한다.
- [x] 상속과 인터페이스를 통해 구현을 간결히 할 수 없는지 고민해 본다.

2022-02-26 02:03 UTC, tmdgusya requested changes
전반적으로 코드가 깔끔하기도 합니다.
여러 학습한 부분들을 코드에 녹여낸거 같아서 좋네요.

다만 네이밍에 관한 부분은 생각을 해보셔야 할 거 같아요.
객체지향 체조를 아마 사다리 미션에서 진행하신걸로 알고 있는데
왜 객체지향 체조에서 기본 타입 대신 랩핑한 타입을 써야 하는가에 대해서 생각해보셔야 할겁니다.
위의 주제를 이해하신다면 UnsignedInt 로 복권 번호를 표현하려 한 것이 좋은 표현은 아니란 걸 알게되실거에요.

두번째로 예외가 많은 것 같은데 더 풍부한 표현을 위해서 커스텀 예외를 한번 학습해보시고 적용시켜보시죠.
커스텀 예외로 표현하게되면 좀 더 읽거나 사용하는 입장에서도 편하게 사용할 수 있습니다.

세번째로 이건 선택사항입니다.
자동 로또 / 수동 로또를 만드는 클래스를 나누는 방법을 한 번 고려해보세요.
예를 들면 LottoMakerInterface 가 있고 그 안에 generateLotto 가 있고, 각각 AutoLottoMaker 와 ManualLottoMaker 가 implements 를 하여 구현하는 식으로요.
꼭 인터페이스가 아니여도 됩니다. 추상클래스를 통해서 하는 방법도 있습니다.
혹은 합성을 이용하셔도 좋아요.

이 과정에서 리스코프 치환원칙에 대해서 공부해보시면 더 더욱 도움이 되실겁니다.

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoBundle.java
> +            throw new IllegalArgumentException("적어도 한 장은 사야 합니다.");
예외가 많은데 커스텀 예외에 관해서 학습해보시고 사용해보시는 건 어떨까요?

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoBundle.java
> +    public void addManualLottoTicket(LottoTicket lottoTicket) {
수동으로 로또를 만들어주는 클래스와, 자동으로 로또를 만들어주는 클래스를 분리하면 어떨까요?
이 과정에서 Interface 또는 추상클래스를 사용해보면서 상속 / 구현 / 합성에 대한 공부를 해볼 수 있을 거 같은데요?
만약 어렵다면 학습만 해보시고 코드에 반영은 안하셔도 됩니다 :)
뭐든 지금 더 잘할수 있는 것들을 학습하는 것 또한 좋은 일이니까요.

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoFactory.java
>      static {
static block 을 사용하셨군요

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoFactory.java
>          IntStream.rangeClosed(LottoNumber.MINIMUM_NUMBER, LottoNumber.MAXIMUM_NUMBER)
적절한 상수와 람다의 활용 괜찮네요.

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoGame.java
> +        // 구매 결과를 출력한다.
주석을 다 달아놓으신거 같은데
제가 읽기에도 메소드명이 괜찮아서 안달아 놓으셔도 될거같은데요?

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoGame.java
> +        List<LottoTicket> lottoTicketList = repeatSupplierUntilSuccessful(() ->
👍

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoGame.java
> +    private <T> T repeatSupplierUntilSuccessful(Supplier<T> supplier) {
좋네요 :)

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoGame.java
> +        try {
다만 Supplier, Consumer 라는 Naming 자체가 로또를 구입하는 도메인을 잘 설명하고 있는지는 모르겠습니다.
사용하고 계시는 코드의 기법이 Supplier, Consumer 이지 그것이 함수의 네이밍까지 귀결되야 하는지는 잘 모르겠네요 
한번 생각해보시죠.

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/domain/LottoNumbers.java
> +                .collect(Collectors.toUnmodifiableList());
오 불변 리스트로 주는군요 ㅎㅎ

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/view/InputView.java
> +        if (input.matches("\\d+(\\s*,\\s*\\d+)*")) {
이 정규식을 상수로 추출해서 어떤 뜻인지도 나타냈으면 좋을거 같은데요?

2022-02-26 02:03 UTC, tmdgusya commented on src/lotto/view/InputView.java
> +        throw new IllegalArgumentException("부호 없는 정수를 입력해야 합니다.");
부호 없는 정수라면 모두 입력되나요? UnsignedInt 라는 네이밍에 대해서 고민해보셔야 할거같은데요?
로또에 몇자리수까지 입력되나요?

2022-02-26 07:53 UTC, astraum commented on src/lotto/domain/LottoBundle.java
> +            throw new IllegalArgumentException("적어도 한 장은 사야 합니다.");
이 프로그램에서 사용한 예외들은 IllegalArgumentException이 적절하다고 생각해서 사용했습니다. 

가급적 기본 제공되는 예외들을 적극적으로 사용하라는 의견도 보았고, 커스텀 예외를 만들어 쓰는 게 편하다는 의견도 보았는데, 로치의 견해도 듣고 싶습니다!

2022-02-26 07:56 UTC, astraum commented on src/lotto/domain/LottoBundle.java
> +    public void addManualLottoTicket(LottoTicket lottoTicket) {
음... 듣고보니 여기서 저는 LottoFacotry를 수동 로또도, 자동 로또도 생산할 수 있는 '만능' 클래스로 작성했다고도 볼 수 있겠네요. 

똑같이 '발행issue'이라는 메시지에 대답하지만, 수동 로또를 발행하는 ManualLottoFatory와 자동 로또를 발행하는 AutoLottoFactory로 행동의 주체를 분리할 수도 있겠군요!

2022-02-26 08:04 UTC, astraum commented on src/lotto/domain/LottoGame.java
> +        // 구매 결과를 출력한다.
저도 주석이 필요없는 코드를 지향하도록 배웠는데, 지난 마스터 클래스에서 호눅스가 주석 좀 달라는 말씀을 하셔서... 오히려 좀 과했나요?

2022-02-26 08:30 UTC, astraum commented on src/lotto/domain/LottoGame.java
> +        try {
돌이켜보면, 메서드 이름을 지을 때 '이 프로그램에서의 역할'에 집중하지 않고 지나치게 일반화시킬 때가 있는 것 같습니다. 한 번 잘 생각해보겠습니다.

2022-02-26 08:31 UTC, astraum commented on src/lotto/domain/LottoNumbers.java
> +                .collect(Collectors.toUnmodifiableList());
한 번 정해지면 내용이 변경되어서는 안 되는 리스트라고 생각했습니다 ㅎㅎ

2022-02-26 08:31 UTC, astraum commented on src/lotto/view/InputView.java
> +        if (input.matches("\\d+(\\s*,\\s*\\d+)*")) {
앗.... 맞네요!

2022-02-26 08:54 UTC, astraum commented on src/lotto/view/InputView.java
> +        throw new IllegalArgumentException("부호 없는 정수를 입력해야 합니다.");
이 부분에 대해서도 제가 InputView의 검증 책임에 대해서 잘못 판단한 것 같다는 생각이 듭니다. 로또 도메인에서 필요로 하는 조건을 입력단으로 전달할지 (i.e. 1~45 사이의 자연수) 아니면 입력단에서는 좀 더 일반적인 범주의 입력만 받아서 로또번호 생성 로직으로 넘길지 고민하다가 결국 후자로 결정했었는데, 좀 더 생각해보니 전자가 더 적절한 접근법이었겠다는 생각이 듭니다. 

repeatSupplier에 관한 피드백에서도 느꼈는데, 기능을 지나치게 일반화시키려고 하는 욕심이 있는 것 같습니다. 보다 목적과 의도에 충실한 코드를 작성하도록 노력하겠습니다.

2022-02-26 10:50 UTC, astraum commented
피드백 감사합니다, 로치! 

짚어주신 주제 - 래퍼 타입, 커스텀 예외, 리스코프 치환 - 에 대해서도 더 공부해 보겠습니다

이번에는 PR을 바로 merge하지 않고 Changes requested 상태로 지정해 주셨는데, 수정 후 리뷰 재요청을 드리면 될까요? 미션 4단계에서 제시된대로 SparkJava를 이용해서 웹 UI를 적용시키는 방법을 공부 중이었는데 3단계 PR 피드백 해결을 우선해야 하나 해서요.

2022-02-26 16:39 UTC, tmdgusya commented on src/lotto/domain/LottoBundle.java
> +            throw new IllegalArgumentException("적어도 한 장은 사야 합니다.");
음 기본 예외를 적극적으로 사용하셔도 좋은데요.
예외가 많아 보여서 이번 기회에 커스텀 예외를 만들어 보면서 학습하시는게 좋을거 같아 리뷰를 드렸습니다 :)
저는 보통 RuntimeException 을 상속하는 편이에요.
IllegalArgumentException 을 상속받으나 RuntimeException 을 상속받으나, 부모 클래스 보다는 자식 클래스의 네이밍으로 도메인을 더 깔끔하게 표현할 수 있다고 생각해서요 ㅎㅎ

LottoException 을 만드는 것 또한 좋은 생각입니다.
좋은 고민을 하고 계시네요. 말씀 하신 방향 다 좋으니 이번 기회에 많은 학습을 할 수 있는 부분들을 생각해서 도전해보세요.

2022-02-26 16:40 UTC, tmdgusya commented on src/lotto/domain/LottoGame.java
> +        // 구매 결과를 출력한다.
음 그런 의도라면 상관없습니다.
근데 메소드 명으로도 충분히 잘 표현하시는 부분이 있어 언급해드린거였어요 ㅎㅎ
결론 칭찬입니다 :) 

주석은 그대로 두시죠 그럼~!

2022-03-01 16:06 UTC, astraum commented
- 커스텀 예외를 만들어보니 내가 원하는 카테고리(= 특정 예외 및 그 예외를 상속하는 서브클래스)의 예외만 따로 캐치해서 처리할 수 있다는 점이 편리했습니다. 또 그 예외에 관련된 정보를 예외 객체의 필드에 담을 수 있다는 점도 유용하게 쓸 수 있을 것 같습니다. 
- 팩토리는 LottoNumberPool을 별도의 클래스로 분리하고 메서드를 정리하다보니 구소련마냥 분해되어 버렸습니다. 
  - LottoNumberPool은 분리하고 나서도 스태틱 유틸 클래스로 사용했는데, 인스턴스화하여 의존성 주입을 시키는 편이 보다 유연한 구조를 만들 수 있지 않았나 하는 생각도 듭니다. 
- 하는 김에 4단계 선택과제인 스파크 자바도 적용해 보았습니다. 
  - 프로그래밍에 입문하여 콘솔 예제만 접하다가 웹 UI를 다루어보니 새롭게 느껴지는 부분이 많았습니다. 
  - 가능하면 html의 form 기능을 최대한 활용하여 브라우저 측에서 최대한 검증된 값을 입력받을 수 있도록 했습니다. 
  - 초보적이나마 JavaScript도 활용하여 입력 필드가 동적으로 생성되도록 만들어 보았습니다.  

로또는 그만 잊고 스프링에 집중하라는 호눅스의 진심어린 조언이 있었지만, 로또 미션을 Change requested 상태로 방치하고 싶지는 않았기 때문에 시간을 쪼개어 급하게나마 마무리 지었습니다. 이번 PR로 끝장을 보려고 브랜치도 따로 나누지 않았고, 서두르다보니 커밋도 많이 뭉뚱그려졌습니다.

2022-03-02 07:04 UTC, merged

2022-03-02 07:04 UTC, tmdgusya commented
고생하셨습니다 :)