[Shine/산토리] 로또 3단계 - 수동구매 기능 추가
codesquad-members-2022/java-lotto pull request #52
Opened 2022-02-25 06:58 UTC by zbqmgldjfh

# 안녕하세요 리뷰어님! 항상 리뷰 해주셔서 감사합니다!

## 이전 feed back 반영하기
- [x] 코드 리뷰 피드백 반영하기
  - [x] `Person` 클래스가 가지고 있는 `LottoTicketSeller` 의존성 없애기
  - [x] `Person` 내부에 불필요한 멤버 변수 제거
  - [x] 6개의 연속된 번호와 보너스 번호를 따로 담는 `WinningNumbers` 객체 만들기

## 질문 1가지
저희 팀은 1급 객체로 LottoTicket을 만들었습니다.

여기서 궁금한 점은, WinningNumbers 객체를 만들면서 1급 객체인 LottoTicket을 상속하는 방법이 떠올랐습니다.
왜냐하면 기존의 1급 객체 에서의 코드를 재사용 하면 중복을 최소화 할 수 있기 때문이었습니다.

하지만 1급 객체는 독립적인 단위로 사용하는 것이다 보니, 상속을 하여 재사용 한다는 것 자체가 확실하지 않았습니다.

이에 대한 리뷰어님의 의견이 궁금합니다!

2022-02-26 09:15 UTC, wheejuni requested changes
수고 많으셨고 전반적으로 잘 구현해 주셨습니다~ 💯 
코멘트 참고해 주시고요.
플젝 전반에서 `List` 와 `ArrayList` 타입 선언이 혼재되어 굉장히 어지러운 모습을 보여주고 있는데요,
[이 링크](https://stackoverflow.com/questions/9852831/polymorphism-why-use-list-list-new-arraylist-instead-of-arraylist-list-n) 한번만 참고해주세요~

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/controller/LottoController.java
> +        int ticketCount = money / TICKET_PRICE;
`seller` 가 금액을 보고 알아서 몇 장 내줄지 판단하게 하는 건 어떨까요?

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/controller/LottoController.java
> +        ArrayList<LottoNumber> lottoNumbers = new ArrayList<>();
꼭 `ArrayList` 타입으로 명시해줄 필요가 있었는지 궁금합니다!

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/controller/LottoController.java
> +    private int[] makeResult(Person customer) {
꼭 배열을 사용할 이유가 있었는지 궁금합니다!

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/domain/LottoNumber.java
> +        return this.number == lottoNumber.number;
`.equals()` 를 오버라이드하는 판단이 더 좋았을 것 같습니다.

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/domain/LottoTicket.java
> +        return result;
스트림 API로 개선할 수 있을 것 같네요.
`.filter()`, `.count()` 를 사용하면 될 것 같아요. 필요에 맞는 종단 처리 메소드가 거의 다 제공되므로 다양한 시나리오에 맞게 잘 찾아서 사용해 보시면 좋겠어요.

2022-02-26 09:15 UTC, wheejuni commented on src/main/java/domain/LottoTicket.java
> +    private int check(LottoNumber numberOfIndex, LottoNumber myNumber) {
위에서 알려드린 방법대로 리팩터링하려면, 여기선 `boolean` 을 리턴해야겠습니다.

2022-02-26 09:22 UTC, wheejuni commented
질문은 별도 코멘트로 답변 드릴게요~

2022-02-26 09:24 UTC, wheejuni commented
중복을 최소화하는 방법으로의 상속 사용에 별로 **동의하지 않습니다**
상속 자체가 안티패턴이라고 보는 시각도 있고요, 코틀린에는 `data class` 가 있는데 `data class` 는 `open class` 가 될 수 없어서 상속받을 수조차 없습니다.

만약 중복을 걷어내고자 하는 방법이라면 상속보다는 합성을 고려해 보시는게 좋겠고요,
비슷한 고민을 담은 [이 글](https://hue-dev.site/engineering/2021/05/20/%EC%83%81%EC%86%8D%EA%B3%BC-%ED%95%A9%EC%84%B1%EC%97%90-%EA%B4%80%ED%95%98%EC%97%AC.html) 을 읽어보시고 해결방안을 고민해 보시면 좋겠어요~ 감사합니다.

2022-02-26 16:57 UTC, seyoung755 commented on src/main/java/controller/LottoController.java
> +        ArrayList<LottoNumber> lottoNumbers = new ArrayList<>();
저희도 프로젝트 진행하면서 해당 부분이 계속 마음에 걸렸습니다..! 제가 미션의 요구사항 중에 ArrayList를 사용해 구현하라는 것을 조금 잘못 이해해서(지금 생각해보니 List의 구현체를 ArrayList로 쓰라는게 아니라 배열 대신 사용해보라는 뜻이었던 것 같습니다.) ArrayList 형태로 LottoNumber를 저장하는 과정에서 단추가 잘못끼워져서 많은 곳에 혼재되었던 것 같습니다. 

리턴 타입이나 매개변수 타입은 List로 선언하여 구현체가 바뀌더라도 설계에 유연성이 생기도록 하는 것이 바람직하다는 걸 참고링크를 보고 다시금 배운 것 같습니다!

2022-02-26 16:59 UTC, seyoung755 commented on src/main/java/controller/LottoController.java
> +    private int[] makeResult(Person customer) {
맞은 개수 별로 result를 저장하기 위해서였습니다. 단순히 맞은 개수의 경우의 수만큼 배열을 선언해두면 index에 접근하기 편해서 배열을 사용했었습니다. 지금 생각해보니 그런 방식으로 구현하더라도 HashMap 등의 선택지도 있었다는 생각이 드네요!

2022-02-26 17:00 UTC, seyoung755 commented on src/main/java/domain/LottoNumber.java
> +        return this.number == lottoNumber.number;
넵,, 심지어 이미 equals()를 사용하고 있기도 했는데 놓쳤네요. 피드백 감사합니다!

2022-02-26 17:01 UTC, seyoung755 commented on src/main/java/domain/LottoTicket.java
> +        return result;
이 부분은 인덴트를 줄이기 위해 나중에 메서드를 분리해서 작성했었는데 그런 방법이 있다는 것도 알게되었네요. 말씀해주신대로 `Intstream`을 활용한다고 생각하니 더 간결해보이는 것 같습니다!

2022-02-27 00:48 UTC, zbqmgldjfh commented on src/main/java/domain/LottoNumber.java
> +        return this.number == lottoNumber.number;
아 그러네요... 이미 equals()를 사용하고 있었다는점을 인식하지 못한 것 같습니다.

2022-02-27 00:51 UTC, zbqmgldjfh commented on src/main/java/controller/LottoController.java
> +        int ticketCount = money / TICKET_PRICE;
원래 Step2 에서는 Seller 가 스스로 몇장을 구매할지 판단하게 되어 있었습니다.
기존 Person은 Seller에 대한 의존성이 있어 Person이 Seller에게 돈을 넘겨주고, 이를 Seller가 스스로 인지하여 티켓을 판매하습니다.
하지면 변경 도중 바뀌게 되었는데, 그 이유는 2가지 입니다.

----
**전략 패턴 사용중 시그니처의 통일**

Composition을 활용한 전략패턴을 Seller가 사용하고 있는데, 이때문에 exchangeTicket 의 시그니처를 random 과 custom 구매 방식에서 동일하게 가게 되었습니다.

수동 구매하기는 사용자의 번호를 전달하면 하나의 LottoTicket을 반환하는 Query 메서드 입니다.
자동 구매는 스스로 Random한 번호를 알고있는 Query 메서드 입니다.
즉, 둘 간의 메서드 시그니처를 동일하게 하다보니, 인자로 Money를 전달할수가 없었습니다.

Random쪽에 파라미터를 만들어 돈을 넘겨주면, 수동 구매 쪽에도 불필요한 파라미터를 만들어야 하기 때문입니다.
문제는 수동은 매번 사용자의 번호를 받아 LottoTicket을 만들어야 하기 때문입니다.

----
**Seller를 생성할 당시에 전달해야 하는가?**

그럼 2번째 방법으로 Seller를 생성할 시점에 인자로 돈을 전달하는 방법이 있을탠데...
Seller가 사용자가 가지고 있는 돈에 대한 정보를 꼭 알아야 할까? 란 의문이 있었습니다.

그냥 seller는 요청할때마다 반환해주면 되는것 아닐까? 곡 Seller도 자신의 상태값으로 money를 가지고 있어야 하나? 란 의문이 있었던것 같습니다.

2022-02-27 00:53 UTC, zbqmgldjfh commented on src/main/java/controller/LottoController.java
> +        ArrayList<LottoNumber> lottoNumbers = new ArrayList<>();
음 요구사항 자체에 "ArrayList를 사용하라" 라는 사항이 있어 이를 준수하기 위해 사용한 것 같습니다.
원래대로 였다면 List를 사용했을 것 같습니다. 

팀원 말대로 단순 1차원 배열 대신 ArrayList를 사용하라는 의미가 아니였을까? 란 생각을 다시 하게 되는것 같습니다.

2022-02-27 00:59 UTC, zbqmgldjfh commented on src/main/java/domain/LottoTicket.java
> +    private int check(LottoNumber numberOfIndex, LottoNumber myNumber) {
아하! 말씀해주신 대로 boolean을 사용하는 것 이 check 라는 메서드의 의미에도 더 적합하다 생각되는 것 같습니다.

2022-02-27 01:13 UTC, zbqmgldjfh commented on src/main/java/controller/LottoController.java
> +    private int[] makeResult(Person customer) {
음, 각 index 별로 알맞은 값을 추가해주면, 예를 들어 
0번 index 에 5개 => 0개 맞은 사람이 5명
1번 index 에 2개 => 1개 맞은 사람이 2명
...
6번 index에 1개 => 6개 모두 맞은 사람이 1명

이런 식으로 간단하게 표현할 수 있다 생각하였기 때문입니다.

혹, 리뷰어님 께서 다른 자료구조를 생각한 것 이라면? 어떤 이유가 있는 것 일까요?
배열로 의미를 잘 전달할 수 있다 생각했는데, Map을 활용하여,
Key : Value 쌍으로 0개 : 5명 , 1개 : 2명, ... , 6개 : 2명 이런 방식으로 했어야 더 적합했을까요??

2022-02-27 11:44 UTC, wheejuni commented on src/main/java/controller/LottoController.java
> +        ArrayList<LottoNumber> lottoNumbers = new ArrayList<>();
요구사항에  _`ArrayList` 를 사용하라_ 고 되어있다면 앞으로는 `java.util.List` 를 사용하라 라는 의미로 해석해주시면 좋을 것 같습니다.

2023-10-14 08:40 UTC, merged