[벅픽 && Hwi] 로또 3단계 - 수동구매 기능 추가
codesquad-members-2022/java-lotto pull request #56
Opened 2022-02-25 11:47 UTC by bugpigg

안녕하세요 Hwi & 벅픽입니다.
3단계 PR 드립니다.
코드 리뷰 해주셔서 감사합니다.

### 기능요구사항
   + [x] 현재 로또 생성기는 자동 생성 기능만 제공한다. 사용자가 수동으로 추첨 번호를 입력할 수 있도록 해야 한다.
   + [x] 입력한 금액, 자동 생성 숫자, 수동 생성 번호를 입력하도록 해야 한다.

### 프로그래밍 요구사항
   + [x] 예외가 발생하는 부분에 대해 자바 Exception을 적용해 예외처리한다.
   + [x] 사용자가 입력한 값에 대한 예외 처리를 철저히 한다.
   + [x] 상속과 인터페이스를 통해 구현을 간결히 할 수 없는지 고민해 본다.

### 아쉬운 점
- 테스트코드 작성을 늦게 시작하여, 많이 작성하지 못했습니다. 
- 의도치 않게 도메인끼리의 메세지교환도 컨트롤러를 통해 이루어 진거 같아, 지금 생각해보니 아쉬운것 같습니다.
- `getter`, `setter`를 사용하여, 1급 컬렉션의 역할을 제대로 구현하지 못한것 같습니다.
- `Composition` 에 대한 이해가 아직 부족한것 같아 이번 미션에서 어설프게 구현된것 같습니다.

2022-02-27 11:35 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
몇가지 코멘트를 참고 부탁 드립니다.

2022-02-27 11:35 UTC, wheejuni commented on src/main/java/domain/LottoMatchChecker.java
> +    private Map<Rank, Integer> winningResult;
`LottoSheet` 이 자신의 당첨 결과를 알고 있으면 안될까요?

2022-02-27 11:35 UTC, wheejuni commented on src/main/java/domain/LottoSheetValidator.java
> +public class LottoSheetValidator {
이 클래스가 수행하는 로직들을 보면 호출되는 곳마다 매번 새로운 객체가 생성되어야 할 필요는 없는 것처럼도 보이네요.
이 객체의 생성자를 숨기고 `static` 메소드를 추가하는 건 어떨까요?

2022-02-27 11:35 UTC, wheejuni commented on src/main/java/domain/ManualLottoSheet.java
> +    public ManualLottoSheet(List<LottoSheet> manualLottoNumbers) throws IllegalArgumentException {
이 클래스의 이름이 `ManualLottoSheet` 인데 파라메터도 `LottoSheet` 타입인게 조금 어색하네요.
제 생각에는 `LottoSheet` 에 자동, 수동 여부를 구분하는 플래그가 보관되어 있고, 번호를 입력받거나 자동으로 생성해서 보관하면 `ManualLottoSheet` 이라는 클래스가 별도로 작성될 이유는 없어보여요. 

전반적으로 이 클래스는 없어져서 `LottoSheet` 에 통합되어야 할 것 같은데 의견이 궁금합니다.

2022-02-27 11:35 UTC, wheejuni commented on src/main/java/domain/ProfitCalculator.java
> +    public ProfitCalculator(int purchasingAmount, Map<Rank,Integer> winningResult) {
`winningResult` 와 `purchasingAmount` 를 입력하면 언제든지 같은 결과값이 반환되는 것인데, 이 클래스 또한 매번 새로운 객체를 생성해야 할 이유는 별로 없어 보입니다.

2022-02-27 11:35 UTC, wheejuni commented on src/main/java/domain/Rank.java
> +                return FIRST;
스트림 API 기반으로 리팩터링 시도해 보세요.

2022-02-28 15:59 UTC, hwicode commented on src/main/java/domain/LottoMatchChecker.java
> +    private Map<Rank, Integer> winningResult;
wheejuni의 말씀을 듣고 보니 `LottoSheet`이 자신의 당첨 결과를 알아야 본인의 역할을 더 잘 수행한다고 느껴지네요. 미션을 진행할 때는 전혀 생각해보지 못한 방식이었습니다.  각 객체의 역할에 대한 생각을 더 많이 해봐야겠네요!!!

2022-02-28 16:35 UTC, hwicode commented on src/main/java/domain/LottoSheetValidator.java
> +public class LottoSheetValidator {
로또 1단계에서도 호눅스에게 `LottoGenerator`의 메소드를 `static`으로 추가해보라는 권유를 받았습니다. 그 때는 별 생각 없이 `static`으로 수정하고 다음 미션을 진행하게 되었는데, 이번에도 같은 피드백을 듣게 되니 생각이 많아졌습니다.

왜 저희가 만든 객체들이 `static`으로 변하는 게 더 나은 지에 대해 개인적으로 생각해봤는데, 각각의 객체들이 자율성이 부족하고 도구의 역할에서 벗어나지 못한다는 생각이 들었습니다. 이는 저희의 코드가 객체지향적이기보다 절차지향적인 측면이 더 많다는 생각이 듭니다. 그래서 이번에 객체지향에 대한 공부 비중을 높여야겠다는 생각이 들었습니다.

이번 주부터 스프링 미션을 시작하게 되었는데 혹시 지금 상황에서 객체지향의 공부비중을 높이는 것이 좋지 못한 생각인지, 아니면 `static`에 대한  저의 생각이 잘못된 것인지 궁금합니다.

2022-02-28 16:41 UTC, hwicode commented on src/main/java/domain/ManualLottoSheet.java
> +    public ManualLottoSheet(List<LottoSheet> manualLottoNumbers) throws IllegalArgumentException {
`ManualLottoSheet` 클래스가 `LottoSheet`에 포괄되는 개념인데 `LottoSheet`가 인자로 들어가는 것이 제가 봐도 이상하네요. 
다시 보니 저도 통합을 하거나 상속을 사용하는 것이 훨씬 나은 것 같습니다!

2022-02-28 16:43 UTC, hwicode commented on src/main/java/domain/Rank.java
> +                return FIRST;
알겠습니다!!

2022-02-28 16:44 UTC, hwicode commented
전체적인 구조에 대해 생각해볼 수 있게 해주셔서 감사합니다. wheejuni!!

2023-03-20 04:19 UTC, merged